# Generated by Django 3.0.2 on 2020-01-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0007_auto_vimeo_obrigatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
